name: 'ghcr-swarm-ssh-deployer'
description: 'Upgrades a service in swarm with new image from GHCR through SSH'
inputs:
  service-name:
    description: 'Name of the service to upgrade'
    required: true
  image:
    description: 'Name of the image to deploy'
    required: true
  image-tag:
    description: 'Name of image tag to deploy'
    required: true
  image-id:
    description: 'Image id (reference) as the full sha256 digest of the image (takes precedence over image-tag when used)'
    required: false
  private-key:
    description: 'Filename to the ssh private key'
    required: true
  username:
    description: 'Username to establish SSH session'
    required: true
  hostname:
    description: 'SSH Hostname'
    required: true
  port:
    description: 'The SSH port to use'
    required: true
  ghcr-username: 
    description: 'The GHCR username'
    required: true
  ghcr-token:
    description: The GHCR token used to read the image to deploy
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
